id: IA80D8A5E
legacy_id: P001695
ocr_import_info:
  bdrc_scan_id: W23259
  source: bdrc
  ocr_info:
    timestamp: '2020-03-25T07:17:54'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T01:01:26.270270+00:00'
last_modified: 2022-09-02 09:01:44.892401
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W23259
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW23259
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: རི་ཆོས་མཚམས་ཀྱི་ཞལ་གདམས།
  author: གནས་མདོ་ཀརྨ་ཆགས་མེད།
statistics:
  ocr_word_mean_confidence_index: 0.7126743058613768
  ocr_word_median_confidence_index: 0.7699999809265137
quality: null
bases:
  I0870:
    source_metadata:
      id: http://purl.bdrc.io/resource/I0870
      total_pages: 840
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I0870.txt
    statistics:
      ocr_word_median_confidence_index: 0.7699999809265137
      ocr_word_mean_confidence_index: 0.7126743058613768
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
