id: P001695
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 2021-12-17 10:15:10.715466
source_metadata:
  id: bdr:W23259
  title: རི་ཆོས་མཚམས་ཀྱི་ཞལ་གདམས
  author: ''
  volumes:
    7ccacd31793749e9bb687ab75fe18b72:
      image_group_id: I0870
      title: ''
      volume_number: 1
      total_pages: 840
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
